#pragma once
#include "FreeFalling.h"
#include "MechanicalMovement.h"
#include "Speed&Acceleration.h"
#include "Frictionforces.h"
#include "GravityWeight.h"
#include <iostream>
#include <cstring>
#include <iomanip>
#include <cmath>
#include <cstring>
#include <time.h>
